"""initial_schema

Revision ID: 6ae014d523ef
Revises: 001
Create Date: 2026-07-25 22:32:16.608835
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '6ae014d523ef'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crop_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('growth_duration_days', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_crop_id'), 'crops', ['crop_id'], unique=True)
    op.create_table('government_schemes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('application_deadline', sa.String(length=20), nullable=True),
    sa.Column('documents_required', sa.JSON(), nullable=True),
    sa.Column('how_to_apply', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_schemes_scheme_id'), 'government_schemes', ['scheme_id'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_slug'), 'product_categories', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_farmer_id'), 'users', ['farmer_id'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('weather_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('weather_type', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_worker_id'), 'workers', ['worker_id'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_conversation_id'), 'ai_conversations', ['conversation_id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('post_type', sa.String(length=20), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_post_id'), 'community_posts', ['post_id'], unique=True)
    op.create_table('equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equipment_id'), 'equipment', ['equipment_id'], unique=True)
    op.create_table('experts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expert_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('speciality', sa.String(length=200), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_consultations', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_expert_id'), 'experts', ['expert_id'], unique=True)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('farming_experience', sa.String(length=50), nullable=True),
    sa.Column('preferred_crops', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmer_profiles_farmer_id'), 'farmer_profiles', ['farmer_id'], unique=True)
    op.create_table('farms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('mandal', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=20), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('water_source', sa.String(length=100), nullable=True),
    sa.Column('irrigation_method', sa.String(length=100), nullable=True),
    sa.Column('farm_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farm_id'), 'farms', ['farm_id'], unique=True)
    op.create_table('loans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('loan_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('emi_amount', sa.Float(), nullable=True),
    sa.Column('outstanding_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_loan_id'), 'loans', ['loan_id'], unique=True)
    op.create_table('login_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('login_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marketplace_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_name', sa.String(length=200), nullable=True),
    sa.Column('delivery_phone', sa.String(length=15), nullable=True),
    sa.Column('estimated_delivery', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_orders_order_id'), 'marketplace_orders', ['order_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=True)
    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=20), nullable=True),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['government_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_applications_application_id'), 'scheme_applications', ['application_id'], unique=True)
    op.create_table('sellers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('shop_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_sales', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellers_seller_id'), 'sellers', ['seller_id'], unique=True)
    op.create_table('user_addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('mandal', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_jti', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_jti'), 'user_sessions', ['token_jti'], unique=True)
    op.create_table('worker_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('consultation_id', sa.String(length=20), nullable=True),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('expert_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.String(length=10), nullable=True),
    sa.Column('scheduled_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_consultation_id'), 'consultations', ['consultation_id'], unique=True)
    op.create_table('delivery_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=20), nullable=True),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('booking_date', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_bookings_booking_id'), 'equipment_bookings', ['booking_id'], unique=True)
    op.create_table('expenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expense_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_expense_id'), 'expenses', ['expense_id'], unique=True)
    op.create_table('farm_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=20), nullable=True),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_name', sa.String(length=200), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_documents_document_id'), 'farm_documents', ['document_id'], unique=True)
    op.create_table('farm_plots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=20), nullable=True),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('plot_name', sa.String(length=200), nullable=False),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('boundary_coordinates', sa.JSON(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farm_plots_plot_id'), 'farm_plots', ['plot_id'], unique=True)
    op.create_table('income_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('income_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('buyer', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('income_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_records_income_id'), 'income_records', ['income_id'], unique=True)
    op.create_table('insurance_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('coverage_amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('end_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_policy_id'), 'insurance_policies', ['policy_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=True),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('transaction_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=20), nullable=True),
    sa.Column('seller_id', sa.String(length=36), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('stock_quantity', sa.Float(), nullable=True),
    sa.Column('min_order_quantity', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.create_table('scheme_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['scheme_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaction_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('worker_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=20), nullable=True),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('booking_date', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=10), nullable=True),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('hours_per_day', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_bookings_booking_id'), 'worker_bookings', ['booking_id'], unique=True)
    op.create_table('crop_cycles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=20), nullable=True),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=True),
    sa.Column('crop_id', sa.String(length=36), nullable=False),
    sa.Column('sowing_date', sa.String(length=10), nullable=True),
    sa.Column('expected_harvest_date', sa.String(length=10), nullable=True),
    sa.Column('actual_harvest_date', sa.String(length=10), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('seed_quantity', sa.Float(), nullable=True),
    sa.Column('seed_unit', sa.String(length=20), nullable=True),
    sa.Column('fertilizer_usage', sa.Text(), nullable=True),
    sa.Column('pesticide_usage', sa.Text(), nullable=True),
    sa.Column('irrigation_schedule', sa.Text(), nullable=True),
    sa.Column('yield_quantity', sa.Float(), nullable=True),
    sa.Column('yield_unit', sa.String(length=20), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_cycle_id'), 'crop_cycles', ['cycle_id'], unique=True)
    op.create_table('farm_journal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('plot_id', sa.String(length=36), nullable=True),
    sa.Column('activity', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('damage_description', sa.Text(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('claim_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_claims_claim_id'), 'insurance_claims', ['claim_id'], unique=True)
    op.create_table('irrigation_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('water_quantity', sa.Float(), nullable=True),
    sa.Column('water_unit', sa.String(length=20), nullable=True),
    sa.Column('irrigation_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['marketplace_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soil_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plot_id', sa.String(length=36), nullable=False),
    sa.Column('ph_level', sa.Float(), nullable=True),
    sa.Column('nitrogen', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('organic_matter', sa.Float(), nullable=True),
    sa.Column('moisture', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['worker_bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=20), nullable=True),
    sa.Column('crop_cycle_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('due_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_tasks_task_id'), 'crop_tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_tasks_task_id'), table_name='crop_tasks')
    op.drop_table('crop_tasks')
    op.drop_table('worker_payments')
    op.drop_table('soil_records')
    op.drop_table('order_items')
    op.drop_table('irrigation_records')
    op.drop_index(op.f('ix_insurance_claims_claim_id'), table_name='insurance_claims')
    op.drop_table('insurance_claims')
    op.drop_table('farm_journal')
    op.drop_index(op.f('ix_crop_cycles_cycle_id'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_worker_bookings_booking_id'), table_name='worker_bookings')
    op.drop_table('worker_bookings')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('scheme_documents')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_insurance_policies_policy_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_income_records_income_id'), table_name='income_records')
    op.drop_table('income_records')
    op.drop_index(op.f('ix_farm_plots_plot_id'), table_name='farm_plots')
    op.drop_table('farm_plots')
    op.drop_index(op.f('ix_farm_documents_document_id'), table_name='farm_documents')
    op.drop_table('farm_documents')
    op.drop_index(op.f('ix_expenses_expense_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_equipment_bookings_booking_id'), table_name='equipment_bookings')
    op.drop_table('equipment_bookings')
    op.drop_table('delivery_tracking')
    op.drop_index(op.f('ix_consultations_consultation_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_table('community_likes')
    op.drop_table('community_comments')
    op.drop_table('budgets')
    op.drop_table('ai_recommendations')
    op.drop_table('worker_reviews')
    op.drop_table('worker_availability')
    op.drop_index(op.f('ix_user_sessions_token_jti'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_addresses')
    op.drop_index(op.f('ix_sellers_seller_id'), table_name='sellers')
    op.drop_table('sellers')
    op.drop_index(op.f('ix_scheme_applications_application_id'), table_name='scheme_applications')
    op.drop_table('scheme_applications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_marketplace_orders_order_id'), table_name='marketplace_orders')
    op.drop_table('marketplace_orders')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_loans_loan_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_farms_farm_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_farmer_profiles_farmer_id'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_experts_expert_id'), table_name='experts')
    op.drop_table('experts')
    op.drop_index(op.f('ix_equipment_equipment_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_community_posts_post_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_ai_conversations_conversation_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_workers_worker_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_farmer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_product_categories_slug'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_government_schemes_scheme_id'), table_name='government_schemes')
    op.drop_table('government_schemes')
    op.drop_index(op.f('ix_crops_crop_id'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
