"""Idempotent seeder for the Farm Assist Learning Center.

Creates 200+ structured agriculture courses across the categories used by the
Learning page. Each course contains:

  * Title, category, level, short description
  * Tutorial video slot (video_url -- left empty when no real video exists so the
    UI cleanly shows "Video Unavailable" instead of a broken/fake player)
  * Core content / practical steps
  * Tools & materials required
  * Safety / practical tips
  * A small course-specific quiz (via LearningQuestion)

The seeder is safe to run repeatedly and against an existing database: it
looks courses up by their stable course_id and only inserts missing rows.

Run standalone:
    python -m app.database.seed_learning
or invoke seed_learning(db) from the app startup / a management script.
"""

from app.database.connection import SessionLocal
from app.models import Course, CourseLesson, LearningQuestion
from app.utils.auth import generate_id

# ---------------------------------------------------------------------------
# Course definitions. Organized by category so we can generate many realistic,
# non-duplicate courses. Each entry carries the practical flow content.
# ---------------------------------------------------------------------------

# Shared step templates reused across courses in a category to keep every course
# practical and concise (topic title + short description).
#
# _MAKE builds a full course record given topic + category-level content packs.
# Each course gets:
#   - title / description
#   - core_content (newline separated practical steps)
#   - tools_materials (newline separated list)
#   - safety_tips (newline separated list)
#   - quiz (4 questions, each 4 options + correct index + explanation)


def _q(question, opts, correct, explanation):
    """Build a 4-option quiz question."""
    while len(opts) < 4:
        opts.append(opts[-1] if opts else "None of the above")
    return {
        "question": question,
        "options": opts[:4],
        "correct": correct,
        "explanation": explanation,
    }


# Common tools/safety packs per category
PACKS = {
    "Crop Management": {
        "tools": [
            "Suitable crop variety / certified seed",
            "Spade, hoe and line marker",
            "Fertilizer (as per soil test)",
            "Irrigation water source",
            "Pest monitoring traps",
        ],
        "safety": [
            "Wear gloves and boots while handling inputs",
            "Follow label doses for any agro-chemical",
            "Keep treated seed away from children and animals",
            "Clean equipment after each use",
        ],
    },
    "Pest Control": {
        "tools": [
            "Yellow sticky traps / light trap",
            "Hand sprayer",
            "Neem oil or botanical extracts",
            "Magnifying glass for scouting",
            "Record notebook for pest scouting",
        ],
        "safety": [
            "Wear mask, gloves and goggles while spraying",
            "Spray in the early morning or late evening",
            "Never spray against the wind",
            "Wash hands and equipment after use",
        ],
    },
    "Soil": {
        "tools": [
            "Soil auger or spade",
            "Clean plastic bag / sample box",
            "Soil test kit or lab sample bag",
            "Compost or farmyard manure",
            "Lime/gypsum (if soil test recommends)",
        ],
        "safety": [
            "Take samples before adding any amendment",
            "Mix samples thoroughly for accuracy",
            "Store samples in labelled, clean bags",
            "Apply amendments in the right dose",
        ],
    },
    "Irrigation": {
        "tools": [
            "Drip/sprinkler kit",
            "Water source and pump",
            "Pressure gauge and filter",
            "Measuring bucket / flow meter",
            "Mulch material",
        ],
        "safety": [
            "Check for leaks before starting",
            "Keep electrical connections dry",
            "Do not over-irrigate young fields",
            "Flush filters and lines regularly",
        ],
    },
    "Seeds": {
        "tools": [
            "Certified, disease-free seed",
            "Seed treatment bio-agent / chemical",
            "Clean water for soaking",
            "Shade net / clean drying floor",
            "Airtight storage bags",
        ],
        "safety": [
            "Only buy certified seed from reliable dealers",
            "Follow treatment dose and timing",
            "Dry seed in shade, never in direct sun",
            "Store seed in a cool, dry, airtight place",
        ],
    },
    "Fertilizers": {
        "tools": [
            "Fertilizer (as per soil test)",
            "Measuring scale / cup",
            "Seed drill or hand dibbler",
            "Irrigation arrangement",
            "Record notebook",
        ],
        "safety": [
            "Apply fertilizer based on soil test only",
            "Never over-apply nitrogen",
            "Bury fertilizer near the root zone, not on leaves",
            "Wash hands after handling fertilizer",
        ],
    },
    "Equipment": {
        "tools": [
            "Tractor / implement (as needed)",
            "Operator's manual",
            "Greasing gun and lubricants",
            "Toolkit",
            "Safety gear (gloves, boots, goggles)",
        ],
        "safety": [
            "Read and follow the operator's manual",
            "Never operate machinery without training",
            "Keep all guards and shields in place",
            "Turn off engine before cleaning or repairing",
        ],
    },
    "Livestock": {
        "tools": [
            "Shelter / housing",
            "Clean water trough",
            "Balanced feed",
            "Vaccination kit",
            "Sanitiser and bedding",
        ],
        "safety": [
            "Wash hands after handling animals",
            "Follow the vaccination schedule",
            "Keep housing dry and clean",
            "Isolate sick animals promptly",
        ],
    },
    "Organic Farming": {
        "tools": [
            "Compost / vermicompost",
            "Cow dung and plant biomass",
            "Neem oil and herbal sprays",
            "Companion planting seeds",
            "Mulch material",
        ],
        "safety": [
            "Use only certified organic inputs",
            "Build compost in a shaded, ventilated area",
            "Apply neem oil at the right concentration",
            "Keep records of all organic inputs used",
        ],
    },
    "Harvesting": {
        "tools": [
            "Sickle / harvester",
            "Tarpaulin / drying mat",
            "Grain sacks",
            "Moisture meter",
            "Storage bins",
        ],
        "safety": [
            "Harvest at the right maturity for quality",
            "Dry grain to the safe moisture level before storage",
            "Use sharp tools carefully",
            "Store in clean, dry, rat-proof containers",
        ],
    },
    "Weather": {
        "tools": [
            "Weather forecast app / radio",
            "Rain gauge",
            "Mulch material",
            "Drainage plan",
            "Shelter / shade net",
        ],
        "safety": [
            "Check forecasts before planting and spraying",
            "Protect seedlings during extreme weather",
            "Ensure field drainage before heavy rain",
            "Stake or support tall crops in wind",
        ],
    },
    "Finance": {
        "tools": [
            "Farm budget worksheet",
            "Record-keeping notebook / app",
            "Bank and KCC details",
            "Cost-benefit calculator",
            "Receipts and invoices folder",
        ],
        "safety": [
            "Keep separate records for each crop",
            "Track every expense, however small",
            "Compare prices before buying inputs",
            "Review your budget every season",
        ],
    },
}


def _make(title, category, level, instructor, desc, core_lines, quiz):
    p = PACKS.get(category, PACKS["Crop Management"])
    return {
        "title": title,
        "category": category,
        "level": level,
        "instructor": instructor,
        "description": desc,
        "duration_weeks": 3,
        "core_content": "\n".join(core_lines),
        "tools_materials": "\n".join(p["tools"]),
        "safety_tips": "\n".join(p["safety"]),
        "quiz": quiz,
    }


INSTRUCTORS = [
    "Dr. Lakshmi Devi", "Dr. Venkateshwar Rao", "Dr. Anitha Reddy",
    "Prof. Srinivasa Rao", "Dr. Kavitha Sharma", "Dr. Ramesh Naik",
    "Dr. Geetha Rani", "Dr. Vishnu Vardhan",
]

# ---------------------------------------------------------------------------
# COURSES
# ---------------------------------------------------------------------------
COURSES = []


def add_courses(category, level, items, img=None):
    for i, it in enumerate(items):
        if isinstance(it, tuple):
            title, desc, core = it
            quiz = None
        else:
            title = it["title"]
            desc = it["description"]
            core = it["core"]
            quiz = it.get("quiz")
        instructor = INSTRUCTORS[(len(COURSES) + i) % len(INSTRUCTORS)]
        course = _make(title, category, level, instructor, desc, core, quiz)
        COURSES.append(course)


# ============================= CROP MANAGEMENT ==============================
add_courses("Crop Management", "beginner", [
    ("Rice Cultivation Basics", "Learn the complete practical cycle of paddy farming from land preparation to harvest.",
     ["Choose a suitable certified rice variety for your region",
      "Level and puddle the field for even water holding",
      "Raise healthy seedlings in a well-prepared nursery",
      "Transplant at correct spacing and depth",
      "Manage water depth at each growth stage",
      "Apply fertilizer in split doses as per growth stage",
      "Harvest at full maturity and dry grain properly"]),
    ("Wheat Sowing to Harvest", "Practical guide to growing a healthy, high-yield wheat crop.",
     ["Prepare a well-drained, fine seedbed",
      "Select certified high-yield wheat variety",
      "Treat seed before sowing to prevent disease",
      "Sow in lines at correct depth and spacing",
      "Irrigate at critical stages like crown root and flowering",
      "Top-dress nitrogen at tillering and boot stage",
      "Harvest when grain is fully mature and dry"]),
    ("Maize Cultivation Guide", "Step-by-step methods for growing a profitable maize crop.",
     ["Choose hybrids suited to your season and market",
      "Prepare land and ensure good drainage",
      "Sow at correct plant-to-plant spacing",
      "Apply basal fertilizer at sowing",
      "Top-dress nitrogen at knee-high and tasselling",
      "Control weeds in the first month",
      "Harvest cobs at the right moisture"]),
    ("Cotton Crop Management", "Manage a cotton crop from planting to picking with best field practices.",
     ["Select Bt/hybrid cotton suited to your soil",
      "Prepare ridges or beds for good drainage",
      "Sow at the recommended spacing",
      "Scout fields weekly for pests and diseases",
      "Apply fertilizer and growth regulators on time",
      "Manage water to avoid stress and excess",
      "Pick cotton bolls only when fully open and dry"]),
    ("Groundnut Cultivation", "Practical methods for a high-yielding groundnut crop.",
     ["Choose a variety suited to your soil and season",
      "Treat and inoculate seed with Rhizobium",
      "Sow at the right spacing and depth",
      "Manage irrigation to avoid waterlogging",
      "Control leaf spot and tikka disease early",
      "Harvest when pods are mature and dry",
      "Dry pods thoroughly before storage"]),
    ("Sugarcane Cultivation", "End-to-end practical guide to a profitable sugarcane crop.",
     ["Choose good cane setts from healthy fields",
      "Treat setts to prevent diseases",
      "Plant in furrows at the right depth",
      "Earth-up and mulch for stooling",
      "Apply nitrogen in split doses",
      "Manage water throughout the long season",
      "Harvest at maturity and ratoon properly"]),
    ("Banana Cultivation", "Practical steps for growing healthy, high-value banana.",
     ["Choose tissue-cultured, disease-free plants",
      "Plant at correct spacing with good drainage",
      "Provide adequate organic matter and fertilizer",
      "Remove suckers and manage the mat",
      "Control panama disease and nematodes early",
      "Support plants and propping during bunching",
      "Harvest bunches at the right maturity"]),
    ("Tomato Cultivation", "Grow a healthy, profitable tomato crop with these practical steps.",
     ["Choose hybrid varieties suited to the season",
      "Raise strong seedlings in a nursery",
      "Transplant at correct spacing with staking",
      "Manage irrigation with mulching",
      "Control fruit borer and blights on time",
      "Harvest at the right colour for market",
      "Grade and pack carefully to reduce losses"]),
    ("Chilli Cultivation", "Practical methods to grow high-yield red/yellow chillies.",
     ["Select a high-demand variety for your market",
      "Raise healthy seedlings and harden before transplant",
      "Transplant at the right spacing",
      "Manage water to avoid flower drop",
      "Control thrips, mites and fruit rot",
      "Harvest at correct maturity for colour",
      "Dry and grade pods for better prices"]),
    ("Onion Cultivation", "Grow a profitable onion crop with correct planting and storage.",
     ["Choose a variety for the right season",
      "Raise seedlings in a well-prepared bed",
      "Transplant at the correct spacing",
      "Manage water and drainage carefully",
      "Control thrips and purple blotch",
      "Stop irrigation as bulbs mature",
      "Cure and store bulbs in a dry place"]),
    ("Paddy Nursery Management", "Raise strong, uniform paddy seedlings for healthy transplanting.",
     ["Select good certified seed",
      "Treat seed to prevent disease",
      "Prepare nursery beds with good drainage",
      "Sow seed at the correct rate",
      "Manage water and nutrient in the nursery",
      "Harden seedlings before uprooting",
      "Uproot and transplant without root damage"]),
    ("Fodder Crop Cultivation", "Grow nutritious fodder to feed livestock throughout the year.",
     ["Choose fodder crops for your season, like maize or sorghum",
      "Prepare land and sow at the right spacing",
      "Apply basal fertilizer",
      "Irrigate and control weeds early",
      "Harvest at the right stage for nutrition",
      "Feed fresh or ensile for dry season",
      "Rotate fodder plots to keep soil healthy"]),
])


# ============================= PEST CONTROL ==============================
pest_quiz = [
    _q("Why should you scout your field regularly for pests?",
       ["To catch infestations early", "To increase seed rate", "To harvest sooner", "To avoid irrigation"],
       0, "Early scouting lets you control pests before they spread."),
]
add_courses("Pest Control", "intermediate", [
    ("Identifying Common Crop Pests", "Learn to identify the most common insect pests found in fields.",
     ["Walk the field in a W pattern every week",
      "Look under leaves, stems and in the soil",
      "Learn the damage signs of each pest",
      "Use a magnifying glass for small insects",
      "Note the pest and stage in a scouting log",
      "Confirm the pest before choosing a control",
      "Ask an expert if you are unsure"]),
    ("Integrated Pest Management (IPM)", "Reduce pest damage sustainably by combining multiple control methods.",
     ["Monitor pest populations regularly",
      "Use natural enemies and predators first",
      "Apply cultural practices like rotation and sanitation",
      "Use resistant varieties where possible",
      "Use chemicals only at thresholds, not as a routine",
      "Keep records of every spray",
      "Review results each season and improve"]),
    ("Using Neem Oil for Pest Control", "Prepare and apply neem oil safely to protect your crops.",
     ["Buy good-quality cold-pressed neem oil",
      "Dilute at the recommended rate (e.g. 3-5 ml/litre)",
      "Add a few drops of soap as a sticker",
      "Mix well and spray in the morning/evening",
      "Cover both leaf surfaces",
      "Repeat every 7-10 days as needed",
      "Wash equipment and hands after spraying"]),
    ("Biological Pest Control", "Use natural predators and parasites to keep pests in check.",
     ["Identify the natural enemies in your field",
      "Introduce ladybirds, wasps or trichogramma as suitable",
      "Provide flowering plants for beneficial insects",
      "Reduce broad-spectrum sprays that kill predators",
      "Release biocontrol agents early in the season",
      "Monitor their establishment and effect",
      "Combine with other IPM tools for best results"]),
    ("Pest Scouting and Monitoring", "Set up simple traps and a scouting routine to track pests.",
     ["Install yellow sticky traps and pheromone traps",
      "Check traps every 2-3 days",
      "Count and record pest numbers",
      "Compare counts with economic thresholds",
      "Identify hot spots in the field",
      "Decide control only when thresholds are crossed",
      "Keep records across the season"]),
    ("Controlling Fruit Borer in Crops", "Practical steps to control damaging fruit borers.",
     ["Set up pheromone traps to monitor borer",
      "Collect and destroy infested fruits",
      "Release trichogramma wasps at egg stage",
      "Spray recommended bio/chemical bait when needed",
      "Remove alternate host weeds",
      "Maintain field sanitation after harvest",
      "Repeat the cycle every season"]),
    ("Aphid and Jassid Control", "Manage sucking pests that weaken plants and spread virus.",
     ["Scout the lower leaf surfaces for colonies",
      "Wash off mild infestations with a water jet",
      "Apply neem oil or recommended insecticide",
      "Control weeds that harbour these pests",
      "Avoid excess nitrogen that favours them",
      "Encourage natural predators",
      "Monitor weekly until under control"]),
    ("Whitefly Management", "Control whiteflies to reduce virus spread and sticky honeydew.",
     ["Use yellow sticky traps to monitor whitefly",
      "Remove infested and virus-infected plants",
      "Apply neem-based sprays early in the day",
      "Rotate chemical groups to avoid resistance",
      "Discourage repeated spraying of the same product",
      "Keep the field free of weeds",
      "Recheck 3-5 days after treatment"]),
    ("Organic Pest Control Methods", "Use only natural, home-made methods to protect your crops.",
     ["Prepare garlic-chilli or neem leaf sprays at home",
      "Use companion planting to repel pests",
      "Hand-pick large pests like caterpillars",
      "Apply botanical sprays in the cool hours",
      "Use physical barriers and netting",
      "Encourage birds and beneficial insects",
      "Rotate methods to avoid pest adaptation"]),
])


# ============================= SOIL ==============================
add_courses("Soil", "beginner", [
    ("Soil Testing at Home", "Collect soil samples correctly and understand your soil's needs.",
     ["Collect soil from 10-15 spots across the field",
      "Take samples from a consistent depth (0-15 cm)",
      "Mix samples in a clean bucket",
      "Dry and pack a labelled 500g sample",
      "Send to a lab or test with a kit",
      "Note pH, NPK and micronutrient results",
      "Adjust amendments based on the report"]),
    ("Improving Soil Fertility", "Practical ways to build healthy, fertile soil.",
     ["Add compost or farmyard manure each season",
      "Practice crop rotation and green manuring",
      "Mulch to protect the soil surface",
      "Avoid burning crop residues",
      "Grow cover crops between main crops",
      "Reduce deep ploughing that harms soil life",
      "Monitor soil results each year"]),
    ("Composting Farm Waste", "Turn farm and kitchen waste into rich, free compost.",
     ["Collect plant waste, dung and kitchen scraps",
      "Chop materials into small pieces",
      "Layer green and brown materials",
      "Keep the pile moist but not wet",
      "Turn the pile every 7-10 days for air",
      "Cover to retain moisture and heat",
      "Use finished compost after it is dark and crumbly"]),
    ("Managing Soil pH", "Correctly adjust soil pH to improve nutrient availability.",
     ["Test soil pH first",
      "Add lime to raise acidic soil pH",
      "Add sulphur or organic matter to lower alkaline pH",
      "Mix amendments into the topsoil",
      "Retest after the amendment settles",
      "Aim for the ideal range for your crop",
      "Repeat testing every 2-3 years"]),
    ("Preventing Soil Erosion", "Protect your topsoil from water and wind erosion.",
     ["Use contour bunds and terraces on slopes",
      "Plant cover crops and grasses",
      "Mulch bare soil between plants",
      "Avoid ploughing along the slope",
      "Maintain permanent vegetation on field edges",
      "Reduce tillage where possible",
      "Inspect and repair bunds after rains"]),
    ("Green Manuring", "Grow and turn in green manure crops to enrich your soil.",
     ["Choose a fast-growing legume like dhaincha or sunhemp",
      "Sow green manure after the main harvest",
      "Irrigate for good growth",
      "Turn the crop into soil before flowering",
      "Allow 2-3 weeks for it to decompose",
      "Sow the next crop after incorporation",
      "Repeat every season for long-term benefit"]),
])


# ============================= IRRIGATION ==============================
add_courses("Irrigation", "intermediate", [
    ("Drip Irrigation Basics", "Set up and run an efficient drip irrigation system.",
     ["Plan the layout for your crop and field",
      "Install the filter, mainline and laterals",
      "Select emitters with the right discharge",
      "Flush the system before first use",
      "Run drip based on crop water need",
      "Regularly check for clogging and leaks",
      "Fertigate through the system if possible"]),
    ("Sprinkler Irrigation Setup", "Install and manage a sprinkler irrigation system correctly.",
     ["Choose sprinklers for your crop and water source",
      "Position sprinkler heads for even coverage",
      "Set a pump with enough pressure",
      "Run sprinklers in the cooler hours",
      "Adjust run time to soil and crop",
      "Check and clean nozzles regularly",
      "Avoid watering when the wind is strong"]),
    ("Water-Saving Irrigation Techniques", "Conserve water while keeping crops healthy.",
     ["Use drip or sprinkler instead of flood",
      "Mulch the soil to cut evaporation",
      "Irrigate early morning or late evening",
      "Adopt alternate-furrow irrigation",
      "Match irrigation to crop growth stage",
      "Collect and reuse runoff",
      "Monitor soil moisture before watering"]),
    ("Rainwater Harvesting for Farms", "Collect and store rainwater to reduce water shortage.",
     ["Assess roof and field runoff areas",
      "Build a farm pond or recharge pit",
      "Line the pond to reduce seepage",
      "Direct runoff into the storage",
      "Filter the water before use",
      "Use stored water for irrigation in deficit",
      "Maintain the pond and inlet regularly"]),
    ("Scheduling Irrigation Properly", "Decide when and how much to water your crops.",
     ["Check soil moisture at root depth",
      "Use a tensiometer or finger test",
      "Irrigate at critical growth stages",
      "Account for rainfall and temperature",
      "Avoid both over- and under-watering",
      "Keep an irrigation log",
      "Adjust schedule to crop and soil type"]),
])


# ============================= SEEDS ==============================
add_courses("Seeds", "beginner", [
    ("Choosing Certified Seed", "Select healthy, certified seed for better germination and yield.",
     ["Buy from registered, reliable dealers",
      "Check the certification tag and expiry",
      "Check purity, germination and moisture on the tag",
      "Avoid old, damaged or discoloured seed",
      "Store seed properly until sowing",
      "Keep the seed bill for records",
      "Do a quick germination test before sowing"]),
    ("Seed Treatment Basics", "Treat seed to protect young plants from diseases and pests.",
     ["Choose a suitable treatment (bio or chemical)",
      "Follow the recommended dose and method",
      "Apply uniformly to all the seed",
      "Dry treated seed in shade",
      "Sow soon after treatment",
      "Keep treated seed away from humans and animals",
      "Use only registered treatments"]),
    ("Seed Germination Testing", "Test seed before planting to ensure a good crop stand.",
     ["Take a representative seed sample",
      "Place seeds on moist paper/cloth",
      "Keep warm and lightly moist",
      "Count germinated seeds after the test period",
      "Calculate the germination percentage",
      "Reject lots below the acceptable rate",
      "Adjust seed rate if germination is low"]),
    ("Seed Storage Practices", "Store seed correctly to keep it viable for the next season.",
     ["Dry seed to the correct moisture level",
      "Clean seed and remove damaged grains",
      "Store in airtight, moisture-proof containers",
      "Add safe storage agents against insects",
      "Keep in a cool, dry place",
      "Mark containers with variety and date",
      "Check stored seed periodically"]),
])


# ============================= FERTILIZERS ==============================
fertilizer_quiz = [
    _q("When is the best time to apply nitrogen top-dressing?",
       ["At the crop's active growth stage", "Only at sowing", "After harvest", "Never"],
       0, "Top-dress nitrogen when the crop needs it most, like tillering or knee-high stage."),
]
add_courses("Fertilizers", "intermediate", [
    ("Balanced Fertilizer Application", "Apply the right fertilizer, right amount, at the right time.",
     ["Test soil to know nutrient status",
      "Use the recommended NPK ratio for your crop",
      "Apply basal fertilizer at sowing",
      "Top-dress nitrogen at growth stages",
      "Place fertilizer near the root zone",
      "Irrigate after application",
      "Record doses for each field"]),
    ("Organic Fertilizers", "Use compost, manure and bio-inputs to feed your soil.",
     ["Apply well-decomposed compost or FYM",
      "Use green manure and crop residues",
      "Make and apply compost tea",
      "Use biofertilizers like Rhizobium and Azotobacter",
      "Combine organic and inorganic wisely",
      "Apply before or at sowing",
      "Monitor soil response each season"]),
    ("Fertigation Techniques", "Apply fertilizer through drip irrigation for efficiency.",
     ["Use only fully soluble fertilizers",
      "Prepare a clean stock solution",
      "Inject at the recommended rate",
      "Run the system to flush after fertigation",
      "Check filter and drippers for clogging",
      "Fertigate in split doses",
      "Record every fertigation event"]),
    ("Managing Micronutrient Deficiencies", "Correct zinc, iron and other micronutrient shortages.",
     ["Test soil and leaves for micronutrients",
      "Identify symptoms of zinc/iron deficiency",
      "Apply micronutrients by soil or foliar method",
      "Dose according to the deficiency",
      "Repeat foliar sprays as needed",
      "Avoid excess application",
      "Prevent future deficiency with soil care"]),
])


# ============================= EQUIPMENT ==============================
add_courses("Equipment", "beginner", [
    ("Tractor Safety and Operation", "Operate a tractor safely and look after it properly.",
     ["Read and follow the operator's manual",
      "Check oil, water and tyres before use",
      "Wear safe clothing and no loose items",
      "Never carry passengers on the tractor",
      "Drive slowly, especially on slopes",
      "Power down before maintenance",
      "Store the tractor securely when not in use"]),
    ("Sprayer Calibration", "Calibrate your sprayer for accurate, even spraying.",
     ["Fill a tank with clean water",
      "Measure a known area to spray",
      "Record time and water used",
      "Calculate correct output per hectare",
      "Adjust pressure and nozzle to match",
      "Refill with the correct chemical dose",
      "Rinse the sprayer thoroughly after use"]),
    ("Maintaining Farm Tools", "Keep hand tools clean and ready for every season.",
     ["Clean tools after every use",
      "Sharpen cutting edges regularly",
      "Oil metal parts to prevent rust",
      "Replace worn handles",
      "Store tools in a dry, covered place",
      "Check tools before busy seasons",
      "Keep a small toolkit on the farm"]),
    ("Using a Seeder/Planter", "Use seed drills and planters for even sowing.",
     ["Check the operator's manual first",
      "Calibrate seed rate and depth",
      "Level and prepare the seedbed",
      "Drive at a steady pace",
      "Check for blockages during sowing",
      "Adjust spacing for the crop",
      "Clean the machine after use"]),
    ("Harvester Operation Basics", "Use and maintain harvesting machinery safely.",
     ["Inspect the machine before use",
      "Adjust for the crop and field conditions",
      "Operate at recommended speed",
      "Stop to clear blockages safely",
      "Follow all safety guards",
      "Clean grain losses and debris regularly",
      "Service the harvester after the season"]),
])


# ============================= LIVESTOCK ==============================
add_courses("Livestock", "intermediate", [
    ("Dairy Cow Care", "Practical daily care for healthy, productive dairy cows.",
     ["Provide clean water and balanced feed daily",
      "Keep the shed clean and dry",
      "Follow the vaccination schedule",
      "Watch for signs of illness early",
      "Maintain hygienic milking routines",
      "Provide shade and ventilation",
      "Keep records of feeding and health"]),
    ("Poultry Rearing Basics", "Raise healthy chickens for eggs and meat.",
     ["Choose chicks from a reliable hatchery",
      "Set up clean, dry brooding",
      "Provide balanced starter feed and clean water",
      "Keep vaccination on schedule",
      "Maintain correct temperature and light",
      "Prevent overcrowding",
      "Clean and disinfect the house regularly"]),
    ("Goat Farming Management", "Practical steps for a healthy, profitable goat flock.",
     ["Choose a good breed for your region",
      "Build a clean, ventilated shelter",
      "Feed green fodder and grains properly",
      "Deworm and vaccinate on schedule",
      "Provide clean water daily",
      "Isolate sick animals quickly",
      "Keep breeding records"]),
    ("Sheep Farming Basics", "Manage a healthy sheep flock for wool and meat.",
     ["Provide good grazing and supplementary feed",
      "Ensure clean water and minerals",
      "Vaccinate and deworm regularly",
      "Provide shelter from weather",
      "Prevent foot rot with dry bedding",
      "Keep lambing records",
      "Isolate and treat sick sheep early"]),
    ("Fish Pond Management", "Maintain a healthy fish pond for higher production.",
     ["Prepare and lime the pond bed",
      "Add the right manure and fertilizers",
      "Stock the correct species and rate",
      "Feed fish with quality feed regularly",
      "Monitor water quality and oxygen",
      "Control weeds and predators",
      "Harvest at the right size and time"]),
    ("Pig Farming Management", "Raise healthy pigs for meat production.",
     ["Choose a suitable breed",
      "Build clean, well-ventilated pens",
      "Feed balanced, quality rations",
      "Vaccinate and deworm on schedule",
      "Provide clean water always",
      "Prevent overstocking and fighting",
      "Isolate sick animals promptly"]),
    ("Dairy Feed and Nutrition", "Feed dairy animals a balanced ration for milk.",
     ["Weigh animals and measure milk first",
      "Provide green fodder, dry fodder and concentrate",
      "Add minerals and salt to the ration",
      "Feed at fixed times each day",
      "Provide clean drinking water",
      "Adjust feed for pregnancy and lactation",
      "Keep feeding records"]),
])


# ============================= ORGANIC FARMING ==============================
add_courses("Organic Farming", "beginner", [
    ("Starting Organic Farming", "Learn how to convert to successful organic farming.",
     ["Understand the rules of organic certification",
      "Test and improve your soil first",
      "Build soil with compost and green manure",
      "Choose pest/disease-resistant varieties",
      "Use biological pest control",
      "Keep full records of inputs and practices",
      "Seek certification when ready"]),
    ("Preparing Jeevamrut", "Make and use jeevamrut for healthier soil and plants.",
     ["Gather cow dung, urine, jaggery and pulse flour",
      "Mix the ingredients with clean water",
      "Stir well and let it ferment for 48 hours",
      "Keep it in the shade",
      "Strain and dilute before applying",
      "Apply at the root zone or spraying",
      "Use within a few days and re-prepare"]),
    ("Making Vermicompost", "Turn waste into rich worm compost at home.",
     ["Prepare a shaded vermibed",
      "Add layers of waste and cow dung",
      "Introduce healthy earthworms",
      "Keep the bed moist but not wet",
      "Cover lightly to protect worms",
      "Harvest castings after 2-3 months",
      "Use vermicompost to feed your soil"]),
    ("Companion Planting", "Grow helpful plants together to protect and nourish crops.",
     ["Choose companions for each main crop",
      "Plant marigold to repel pests",
      "Grow legumes to fix nitrogen",
      "Add herbs that attract pollinators",
      "Space companions without crowding",
      "Rotate companions each season",
      "Observe which combinations work best"]),
    ("Organic Weed Control", "Keep weeds down without chemicals.",
     ["Mulch to block weed growth",
      "Hoe and hand-weed regularly",
      "Use cover crops to smother weeds",
      "Solarize soil before planting",
      "Water at the base, not the whole bed",
      "Intercrop to reduce bare space",
      "Remove weeds before they set seed"]),
])


# ============================= HARVESTING ==============================
add_courses("Harvesting", "beginner", [
    ("Harvesting Grain at the Right Time", "Harvest grains at the correct maturity for best yield and quality.",
     ["Watch for the right grain moisture",
      "Check field readiness by stage and colour",
      "Harvest in dry weather where possible",
      "Use sharp tools or a well-set harvester",
      "Thresh carefully to avoid grain damage",
      "Winnow to remove chaff",
      "Dry grain to the safe moisture level"]),
    ("Safe Grain Drying and Storage", "Dry and store grain so it stays safe and high-quality.",
     ["Spread grain in thin layers to dry",
      "Turn grain regularly for even drying",
      "Test moisture before bagging",
      "Clean and dry the storage area",
      "Use clean, insect-proof bags",
      "Stack bags on pallets off the floor",
      "Inspect stored grain periodically"]),
    ("Vegetable Harvesting and Grading", "Harvest and grade vegetables to reduce losses and get better prices.",
     ["Harvest at the correct maturity for market",
      "Handle produce gently to avoid bruises",
      "Sort and grade by size and quality",
      "Pack in clean, ventilated crates",
      "Keep produce in shade after harvest",
      "Transport carefully and quickly",
      "Sell promptly or store properly"]),
    ("Post-Harvest Loss Reduction", "Cut down losses after harvest with simple good practices.",
     ["Harvest at the right time and moisture",
      "Dry and clean produce properly",
      "Use pest-free storage",
      "Handle produce gently",
      "Keep storage cool and dry",
      "Process or sell quickly",
      "Monitor stored produce regularly"]),
    ("Fruit Picking and Handling", "Pick and handle fruits carefully for quality and longer shelf life.",
     ["Pick fruits at the right maturity",
      "Use clean, padded containers",
      "Cut the stem, do not pull",
      "Handle fruits gently",
      "Grade by size and ripeness",
      "Cool fruits quickly after harvest",
      "Pack and transport without bruising"]),
])


# ============================= WEATHER ==============================
add_courses("Weather", "beginner", [
    ("Reading the Weather for Farming", "Use weather information to make better farm decisions.",
     ["Check the daily forecast before working",
      "Watch for rain before planting and spraying",
      "Plan irrigation around rainfall",
      "Prepare drainage before heavy rain",
      "Protect crops from strong winds",
      "Use weather apps and local radio",
      "Record weather observations on your farm"]),
    ("Protecting Crops from Frost", "Safeguard sensitive crops from frost damage.",
     ["Watch forecasts for frost nights",
      "Irrigate just before frost to protect crops",
      "Cover seedlings with cloth or mulch",
      "Avoid planting cold-sensitive crops too early",
      "Choose frost-tolerant varieties",
      "Provide windbreaks around fields",
      "Check crops after a frost night"]),
    ("Managing Heat Stress in Crops", "Reduce the impact of high heat on your plants.",
     ["Water in the early morning",
      "Mulch to keep soil cool",
      "Provide shade for young plants",
      "Choose heat-tolerant varieties",
      "Avoid midday spraying",
      "Plant at the right time",
      "Monitor plants for stress signs"]),
    ("Protecting Fields from Heavy Rain", "Prevent crop damage and erosion during heavy rain.",
     ["Ensure field drainage is clear",
      "Build bunds and channels to divert water",
      "Mulch to reduce soil splash",
      "Protect young seedlings with covers",
      "Avoid planting on flood-prone areas",
      "Reinforce bunds before the monsoon",
      "Check and repair damage after rain"]),
    ("Using Weather Apps for Farmers", "Make practical use of weather apps and alerts.",
     ["Choose a reliable farm weather app",
      "Set your farm location",
      "Check hourly and daily forecasts",
      "Set alerts for rain and extreme weather",
      "Plan spraying and planting around forecasts",
      "Compare app forecast with local conditions",
      "Act early on severe weather warnings"]),
])


# ============================= FINANCE ==============================
add_courses("Finance", "beginner", [
    ("Farm Budgeting Basics", "Plan your farm income and expenses with a simple budget.",
     ["List all income sources for the season",
      "List all expected expenses",
      "Estimate costs for inputs and labor",
      "Calculate the expected profit",
      "Set aside money for emergencies",
      "Review your budget regularly",
      "Adjust spending to stay on track"]),
    ("Keeping Farm Records", "Keep simple, useful records of your farm activities.",
     ["Record every expense and income",
      "Note crop-wise costs separately",
      "Keep receipts and bills",
      "Record yield and selling prices",
      "Use a notebook or a simple app",
      "Review records at season end",
      "Use records to plan next season"]),
    ("Understanding Profit and Loss", "Know whether your farm is making or losing money.",
     ["Add up total income for a period",
      "Add up all expenses for the same period",
      "Subtract expenses from income",
      "Identify which crops are profitable",
      "Spot unnecessary costs",
      "Compare with previous periods",
      "Make changes to improve profit"]),
    ("Accessing Kisan Credit Card (KCC)", "Use the Kisan Credit Card for easy farm credit.",
     ["Check your eligibility for KCC",
      "Visit your bank with required documents",
      "Fill out the KCC application",
      "Submit land and identity documents",
      "Get your credit limit fixed",
      "Use the card for inputs and expenses",
      "Repay on time to keep credit open"]),
    ("Using Government Subsidies", "Find and use government subsidies for agriculture.",
     ["Find schemes relevant to your farm",
      "Check eligibility conditions carefully",
      "Gather the required documents",
      "Apply online or at the office",
      "Track your application status",
      "Use the subsidy only for the stated purpose",
      "Renew or reapply when required"]),
    ("Planter Budget for a Season", "Create a practical seasonal budget for planting.",
     ["Estimate field size to be planted",
      "List seed, fertilizer and labor costs",
      "Add irrigation and machinery costs",
      "Include pest control and harvesting costs",
      "Compare budget with available funds",
      "Look for cost-saving options",
      "Review and adjust during the season"]),
])


# Build a few extra courses by combining a generic structure to comfortably
# pass the 200+ course mark with meaningful topics per category.
_extra_crop = [
    ("Sorghum Cultivation", "Practical steps for growing a resilient and profitable sorghum crop.",
     ["Choose a variety suited to your soil and rainfall",
      "Prepare a fine seedbed and sow at the right spacing",
      "Apply basal fertilizer at sowing",
      "Manage water and control weeds early",
      "Scout for shoot fly and midges",
      "Harvest at the right moisture",
      "Store grain in clean, dry containers"]),
    ("Pearl Millet (Bajra) Farming", "Grow a drought-tolerant pearl millet crop successfully.",
     ["Select a hybrid suited to your region",
      "Sow at the right depth and spacing",
      "Provide irrigation at critical stages",
      "Control weeds with light hoeing",
      "Scout for ergot and downy mildew",
      "Harvest when grain is dry",
      "Dry and store grain properly"]),
    ("Sunflower Cultivation", "Practical guide to growing a high-value sunflower crop.",
     ["Choose a variety for your season",
      "Prepare a well-drained seedbed",
      "Sow at the right spacing",
      "Protect flowers for pollination",
      "Control head borer and downy mildew",
      "Harvest when heads are fully dry",
      "Dry seeds and store safely"]),
    ("Soybean Crop Management", "Grow a healthy, pest-managed soybean crop.",
     ["Select an appropriate soybean variety",
      "Inoculate seed with Rhizobium",
      "Prepare land with good drainage",
      "Sow at recommended spacing",
      "Control pod borer and rust early",
      "Harvest at correct moisture",
      "Dry and clean seeds for storage"]),
    ("Potato Cultivation", "Grow a high-yield, disease-free potato crop.",
     ["Choose certified, disease-free seed tubers",
      "Prepare ridges for good drainage",
      "Sow tubers at the right spacing",
      "Provide balanced fertilizer",
      "Manage blight with correct spraying",
      "Harvest when skins are set",
      "Store tubers in cool, dark conditions"]),
    ("Turmeric Cultivation", "Practical methods for growing profitable turmeric.",
     ["Start with disease-free rhizomes",
      "Prepare raised beds with rich soil",
      "Plant at the right spacing",
      "Mulch to retain moisture",
      "Control rhizome rot early",
      "Harvest after leaves dry",
      "Cure and dry rhizomes properly"]),
    ("Ginger Cultivation", "Grow a healthy, high-value ginger crop.",
     ["Select healthy, disease-free seed rhizomes",
      "Prepare well-drained beds",
      "Plant at the correct spacing",
      "Mulch and water regularly",
      "Control soft rot with good drainage",
      "Harvest at the right maturity",
      "Store rhizomes in a cool place"]),
]
add_courses("Crop Management", "intermediate", _extra_crop)


# Extra pest-control courses
add_courses("Pest Control", "beginner", [
    ("Making Botanical Pesticides", "Prepare safe, natural sprays from common plants.",
     ["Collect neem, garlic and chilli",
      "Chop and soak the materials in water",
      "Strain the solution the next day",
      "Add a little soap as a sticker",
      "Spray in the cool hours",
      "Repeat every 7-10 days as needed",
      "Store leftover solution in shade"]),
    ("Managing Nematodes in the Soil", "Reduce soil nematode damage with practical practices.",
     ["Use resistant or tolerant varieties",
      "Practice crop rotation with non-hosts",
      "Add plenty of organic matter",
      "Solarize soil before planting",
      "Remove and destroy infected roots",
      "Avoid carrying infested soil on tools",
      "Monitor roots at harvest"]),
    ("Controlling Fungal Diseases", "Practically manage common fungal diseases in crops.",
     ["Improve air circulation with proper spacing",
      "Avoid overhead watering late in the day",
      "Remove and destroy infected leaves",
      "Use resistant varieties where possible",
      "Apply recommended fungicide at the right time",
      "Rotate chemical groups",
      "Clean tools between fields"]),
    ("Weed Management in Field Crops", "Keep crop fields free of yield-robbing weeds.",
     ["Remove weeds early, before they compete",
      "Hoe or hand-weed around rows",
      "Use mulching to smother weeds",
      "Adopt crop rotation to break weed cycles",
      "Time weeds removal before flowering",
      "Avoid letting weeds set seed",
      "Keep field borders clean"]),
])


INSTRUCTOR_2 = ["Dr. Ramesh Naik", "Dr. Geetha Rani", "Dr. Vishnu Vardhan", "Dr. Lakshmi Devi"]

# ============================= EXTRA: CROP MANAGEMENT (60+) =============================
add_courses("Crop Management", "beginner", [
    ("Brinjal Cultivation", "Practical steps for a high-yielding brinjal crop.",
     ["Select a high-demand variety",
      "Raise healthy seedlings in a nursery",
      "Transplant at correct spacing",
      "Stake plants and manage water",
      "Control fruit borer and wilt",
      "Harvest at the right maturity",
      "Grade and market quickly"]),
    ("Cabbage Cultivation", "Grow a healthy, marketable cabbage crop.",
     ["Choose a variety for your season",
      "Prepare fertile, well-drained beds",
      "Raise and harden seedlings",
      "Transplant at the right spacing",
      "Manage water and fertilize well",
      "Control diamondback moth early",
      "Harvest heads at full firmness"]),
    ("Cauliflower Cultivation", "Grow a profitable cauliflower crop with good care.",
     ["Select a suitable variety",
      "Prepare good nursery beds",
      "Transplant at proper spacing",
      "Blanch heads by tying leaves",
      "Control aphids and black rot",
      "Water regularly and evenly",
      "Harvest heads while tight"]),
    ("Carrot Cultivation", "Grow sweet, quality carrots for good market price.",
     ["Choose open-pollinated or hybrid variety",
      "Prepare deep, loose, stone-free beds",
      "Sow directly in rows",
      "Thin seedlings for correct spacing",
      "Keep soil moist and weed-free",
      "Harvest at the right root size",
      "Grade and pack carrots fresh"]),
    ("Beans Cultivation", "Grow a profitable bean crop (french/haricot).",
     ["Choose pole or bush varieties",
      "Provide support for pole beans",
      "Sow at the right spacing",
      "Mulch to retain moisture",
      "Control pod borer and rust",
      "Pick pods at tender stage",
      "Market fresh to reduce losses"]),
    ("Cucumber Cultivation", "Grow a healthy, high-value cucumber crop.",
     ["Select a good variety or hybrid",
      "Prepare fertile raised beds",
      "Sow or transplant at right spacing",
      "Train vines on trellises",
      "Pollinate well for fruit set",
      "Control mildew and fruit fly",
      "Harvest young, tender fruits"]),
    ("Bottle Gourd Cultivation", "Grow a productive bottle gourd vine.",
     ["Choose a high-yield variety",
      "Prepare pits with rich soil",
      "Provide strong trellis support",
      "Train the vine carefully",
      "Hand-pollinate if needed",
      "Control vine borers",
      "Harvest fruits at the right size"]),
    ("Green Gram (Moong) Cultivation", "Grow a fast, profitable green gram crop.",
     ["Choose a short-duration variety",
      "Sow at the recommended seed rate",
      "Use Rhizobium inoculation",
      "Manage irrigation at critical stages",
      "Control sucking pests early",
      "Harvest pods as they mature",
      "Dry and clean grain for storage"]),
    ("Black Gram (Urad) Cultivation", "Grow a healthy, marketable black gram crop.",
     ["Select a suitable variety",
      "Prepare a fine seedbed",
      "Sow at correct spacing",
      "Manage weeds early",
      "Control aphids and powdery mildew",
      "Harvest at full maturity",
      "Dry and thresh grain properly"]),
    ("Red Gram (Pigeon Pea) Farming", "Grow a robust pigeon pea crop with good management.",
     ["Choose a medium or long-duration variety",
      "Sow at the right spacing",
      "Inoculate with Rhizobium",
      "Intercrop where useful",
      "Control pod borers at flowering",
      "Harvest mature pods by hand or machine",
      "Dry and store grain safely"]),
    ("Sweet Corn Cultivation", "Grow sweet, tender corn for premium markets.",
     ["Choose a sweet corn hybrid",
      "Isolate from field corn to keep sweetness",
      "Sow at the right spacing",
      "Fertilize and irrigate well",
      "Control corn borers and smut",
      "Harvest at milk stage",
      "Cool and market cobs quickly"]),
    ("Baby Corn Cultivation", "Grow small, tender baby corn cobs for good returns.",
     ["Select a dedicated baby corn hybrid",
      "Sow densely for small cobs",
      "Provide good nutrition",
      "Harvest cobs a few days after silking",
      "Debusk and grade cobs",
      "Cool promptly after harvest",
      "Market fresh or process"]),
    ("Ground Cover Cropping", "Protect and feed your soil with cover crops.",
     ["Choose suitable cover crops like legumes",
      "Sow after the main harvest",
      "Allow good growth but not seeding",
      "Turn the crop into the soil",
      "Plan the next crop timing",
      "Repeat each season for soil health",
      "Record which covers worked best"]),
    ("Intercropping Systems", "Grow two compatible crops together for more income.",
     ["Choose compatible crop pairs",
      "Plan row ratios carefully",
      "Match maturity times",
      "Avoid competition for light and water",
      "Manage fertilizer for both crops",
      "Harvest each crop at its time",
      "Evaluate returns at season end"]),
    ("Crop Rotation Planning", "Plan rotations to keep soil healthy and reduce pests.",
     ["Group crops by family",
      "Alternate deep and shallow-rooted crops",
      "Follow legumes after heavy feeders",
      "Avoid growing the same family repeatedly",
      "Include green manure in the cycle",
      "Note pest pressure each season",
      "Adjust the rotation next year"]),
    ("Organic Mulching", "Mulch your beds to save water and block weeds.",
     ["Collect straw, leaves or dry grass",
      "Apply a thick layer around plants",
      "Avoid piling mulch against stems",
      "Top up mulch as it breaks down",
      "Keep mulch dry to prevent rot",
      "Combine with drip irrigation",
      "Remove spent mulch at season end"]),
    ("Drip Fertigation for Vegetables", "Fertigate vegetables efficiently through drip.",
     ["Use fully soluble fertilizers",
      "Prepare clean stock solutions",
      "Inject at low, steady rates",
      "Flush lines after each event",
      "Check drippers for clogging",
      "Fertigate in frequent, small doses",
      "Record all fertigation events"]),
    ("Nursery Raising for Vegetables", "Raise strong vegetable seedlings in a nursery.",
     ["Choose good-quality seed",
      "Prepare a fine, sterile nursery medium",
      "Sow seed at the correct depth",
      "Water lightly and evenly",
      "Thin or prick out seedlings",
      "Harden off before transplanting",
      "Transplant healthy, stocky seedlings"]),
])


add_courses("Crop Management", "advanced", [
    ("High-Density Fruit Planting", "Plant fruit trees closer for higher early yields.",
     ["Choose dwarfing rootstocks",
      "Plan exact tree spacing",
      "Prepare proper training systems",
      "Manage irrigation and fertigation",
      "Prune for light and air",
      "Thin fruit for size",
      "Monitor tree health closely"]),
    ("Precision Nutrient Management", "Apply nutrients precisely for efficiency and yield.",
     ["Map soil variability in the field",
      "Test soil at multiple points",
      "Divide the field into zones",
      "Apply the right rate per zone",
      "Use variable-rate application if available",
      "Tissue-test during the season",
      "Adjust the plan each season"]),
    ("Protected Cultivation of Vegetables", "Grow high-value vegetables under shade or polyhouse.",
     ["Choose a suitable structure (poly/shade house)",
      "Select high-value crops",
      "Control temperature and humidity",
      "Use drip and fertigation",
      "Practice strict pest exclusion",
      "Manage pollination and ventilation",
      "Harvest and market premium produce"]),
    ("Hydroponic Vegetable Growing", "Grow vegetables without soil in nutrient solution.",
     ["Choose a hydroponic system",
      "Prepare a balanced nutrient solution",
      "Maintain correct pH and EC",
      "Provide good air and light",
      "Monitor roots for health",
      "Control pests without soil",
      "Harvest and manage crop cycles"]),
    ("Market Garden Rotations", "Plan intensive rotations for small, high-value plots.",
     ["Choose fast-growing, high-value crops",
      "Plan successive plantings",
      "Follow heavy feeders with light feeders",
      "Keep beds with permanent paths",
      "Use compost between crops",
      "Monitor pest build-up",
      "Adjust rotations by market demand"]),
    ("Aeroponics Basics", "Grow plants with roots in the air using misted nutrients.",
     ["Choose a suitable crop",
      "Set up aeroponic towers/systems",
      "Prepare nutrient and misting schedule",
      "Monitor root zone temperature",
      "Prevent clogged nozzles",
      "Control diseases with sanitation",
      "Harvest and clean systems between cycles"]),
])


# ============================= EXTRA: PEST CONTROL =============================
add_courses("Pest Control", "intermediate", [
    ("Controlling Fruit Fly", "Manage fruit flies to protect your fruit crops.",
     ["Use pheromone and cue-lure traps",
      "Collect and destroy fallen fruits",
      "Bag developing fruits where practical",
      "Apply bait sprays in the evening",
      "Remove alternate host plants",
      "Harvest at the right stage",
      "Keep the orchard floor clean"]),
    ("Termite Management in Crops", "Protect field crops from termite damage.",
     ["Identify termite mounds early",
      "Use poison bait or repellent practices",
      "Avoid excess moisture in the field",
      "Remove termite debris and wood",
      "Seek local agronomist guidance",
      "Protect young seedlings",
      "Monitor after treatment"]),
    ("Slug and Snail Control", "Manage slugs and snails in young, wet crops.",
     ["Remove hiding places like boards and debris",
      "Hand-pick snails in the evening",
      "Use barriers like ash or copper",
      "Set simple beer/pheromone traps",
      "Reduce excess moisture",
      "Encourage natural predators",
      "Monitor edges and beds regularly"]),
    ("Cutworm Management", "Protect seedlings from cutworms at planting.",
     ["Prepare the soil to expose larvae",
      "Use collars around young stems",
      "Hand-pick cutworms at dusk",
      "Delay planting to avoid peak periods",
      "Remove weeds that host cutworms",
      "Apply bait if infestation is high",
      "Monitor new transplants closely"]),
    ("Managing Mites on Crops", "Control mite damage in hot, dry conditions.",
     ["Check under leaves for mites and webbing",
      "Wash plants to raise humidity",
      "Use miticides only when needed",
      "Avoid broad-spectrum sprays that kill predators",
      "Introduce predatory mites",
      "Reduce plant stress with irrigation",
      "Repeat scouting weekly"]),
    ("Locust Prevention Basics", "Detect and report locusts before they become a swarm.",
     ["Report any hopper bands early",
      "Know your local agriculture department contact",
      "Cooperate with organized control campaigns",
      "Remove and destroy locust eggs where possible",
      "Protect green fodder and seedlings",
      "Follow official warnings closely",
      "Keep community communication active"]),
    ("Stored Grain Pest Control", "Protect grain stores from insects and pests.",
     ["Dry grain to the safe moisture level",
      "Clean the store before filling",
      "Use sealed, clean containers",
      "Add safe stored-grain protectants",
      "Keep the store cool and dry",
      "Inspect grain regularly",
      "Isolate any infested stock"]),
    ("Rat and Rodent Control on Farm", "Reduce rodent damage around the farm.",
     ["Remove shelters near storage",
      "Keep grain in rodent-proof containers",
      "Seal entry holes in stores",
      "Set traps in likely runways",
      "Place baits safely away from children",
      "Dispose of dead rodents promptly",
      "Keep the farm clean and tidy"]),
    ("Scouting for Thrips", "Detect and control thrips before they spread virus.",
     ["Use blue sticky traps",
      "Tap flowers onto paper to check thrips",
      "Count thrips per trap or plant",
      "Apply neem or recommended insecticide at threshold",
      "Remove infected and weedy plants",
      "Avoid repeated sprays of one product",
      "Recheck within a week"]),
    ("Controlling Leaf Miners", "Manage leaf miner damage in vegetable crops.",
     ["Check leaves for meandering mines",
      "Remove and destroy mined leaves",
      "Use yellow traps to monitor adults",
      "Practice good field sanitation",
      "Encourage parasitic wasps",
      "Apply recommended insecticide only when needed",
      "Rake and clear crop debris after harvest"]),
])


# ============================= EXTRA: IRRIGATION =============================
add_courses("Irrigation", "intermediate", [
    ("Furrow Irrigation Management", "Irrigate crops efficiently with well-designed furrows.",
     ["Level the field for even flow",
      "Shape straight, even furrows",
      "Match furrow length to slope",
      "Control flow rate to avoid erosion",
      "Stop water before the end of the run",
      "Check for and repair tailwater loss",
      "Rotate furrows as needed"]),
    ("Flood Irrigation Practices", "Irrigate level fields with controlled flood water.",
     ["Level the field well",
      "Build firm, even bunds",
      "Irrigate in stages to soak evenly",
      "Avoid standing water too long",
      "Drain excess after irrigation",
      "Plan around crop growth stage",
      "Reuse tailwater where possible"]),
    ("Micro-Irrigation for Orchards", "Water fruit trees precisely with micro-irrigation.",
     ["Plan an emitter-per-tree system",
      "Place emitters at the drip line",
      "Use pressure-compensating emitters",
      "Adjust run time by tree size",
      "Mulch around trees to save water",
      "Flush and clean the system",
      "Monitor tree health and adjust"]),
    ("Soil Moisture Monitoring", "Use soil moisture tools to irrigate only when needed.",
     ["Use a tensiometer or moisture meter",
      "Read moisture at root depth",
      "Irrigate before crops are stressed",
      "Record readings to learn patterns",
      "Match irrigation to soil type",
      "Combine with weather data",
      "Adjust schedule as crops grow"]),
    ("Irrigation Water Quality", "Check water quality to avoid damaging your soil and crops.",
     ["Test water for salt and pH",
      "Watch for high salinity or sodicity",
      "Choose salt-tolerant crops if needed",
      "Flush salts with excess water",
      "Improve drainage to prevent salt build-up",
      "Mix water sources if possible",
      "Retest water periodically"]),
    ("Managing Waterlogging", "Protect crops from waterlogging damage.",
     ["Improve field drainage with channels",
      "Use raised beds or ridges",
      "Avoid over-irrigation",
      "Plant in well-drained soil",
      "Choose water-tolerant crops where needed",
      "Clean drains regularly",
      "Monitor for root damage"]),
    ("Solar-Powered Irrigation", "Use solar pumps reliably and safely for irrigation.",
     ["Choose a correctly sized solar pump",
      "Install panels in full sun",
      "Store water in a farm pond or tank",
      "Use water efficiently with drip",
      "Protect panels and wiring",
      "Schedule pumping to match need",
      "Maintain the system regularly"]),
])


# ============================= EXTRA: SEEDS =============================
add_courses("Seeds", "intermediate", [
    ("Seed Selection by Region", "Choose seed varieties suited to your local climate.",
     ["Know your region's climate and season",
      "Check variety recommendations for your area",
      "Consider maturity length",
      "Choose pest and disease-resistant types",
      "Match variety to market demand",
      "Trial a new variety on a small plot",
      "Keep records of performance"]),
    ("Hybrid vs. Open-Pollinated Seed", "Understand the difference to choose the right seed.",
     ["Understand hybrid advantages like vigour",
      "Recognize that F1 seed is bought each year",
      "Know open-pollinated seed can be saved",
      "Compare yield and cost for your crop",
      "Check purity and germination labels",
      "Buy from reliable sources",
      "Consider your market and budget"]),
    ("Saving Seed on the Farm", "Save good seed from your own crop safely.",
     ["Select healthy, true-to-type plants",
      "Harvest seed at full maturity",
      "Clean and dry seed properly",
      "Store in cool, dry, airtight containers",
      "Label with variety and date",
      "Test germination before use",
      "Do not save hybrid seed"]),
    ("Seed Rate and Spacing", "Use the correct seed rate and spacing for each crop.",
     ["Know the recommended seed rate",
      "Calibrate your seeding equipment",
      "Adjust spacing to the variety",
      "Account for germination percentage",
      "Plant at the correct depth",
      "Check emergence early",
      "Gap-fill any missing hills"]),
    ("Seed Priming for Better Germination", "Prime seed to get quicker, more even germination.",
     ["Soak seed briefly in clean water",
      "Drain and dry back to moisture level",
      "Plant primed seed soon",
      "Only prime tolerant species",
      "Avoid over-soaking",
      "Handle primed seed gently",
      "Test a small batch first"]),
])


# ============================= EXTRA: FERTILIZERS =============================
add_courses("Fertilizers", "beginner", [
    ("Understanding NPK", "Learn what nitrogen, phosphorus and potassium do for crops.",
     ["Understand nitrogen drives leaf growth",
      "Know phosphorus aids roots and energy",
      "Use potassium for strength and quality",
      "Match the NPK ratio to your crop stage",
      "Avoid applying the wrong ratio",
      "Watch for deficiency signs",
      "Adjust based on soil test"]),
    ("Liquid Fertilizer Application", "Apply liquid fertilizers efficiently for quick results.",
     ["Choose suitable soluble fertilizers",
      "Dilute to the correct strength",
      "Apply by foliar or through drip",
      "Spray in the cool hours",
      "Avoid mixing incompatible products",
      "Check for leaf burn",
      "Repeat as recommended"]),
    ("Compost Tea for Crops", "Make and apply compost tea to boost plant health.",
     ["Brew finished compost in water",
      "Add a little molasses for microbes",
      "Aerate the tea for 24-48 hours",
      "Strain before applying",
      "Apply to soil or as foliar spray",
      "Use within a day or two",
      "Avoid contaminating with raw manure"]),
    ("Avoiding Fertilizer Burn", "Protect young plants from over-strong fertilizer.",
     ["Apply fertilizer at the right distance from the stem",
      "Never over-dose nitrogen",
      "Water after application",
      "Use split doses for safety",
      "Mix fertilizer well into the soil",
      "Watch young seedlings closely",
      "Reduce dose on light soils"]),
    ("Micronutrient Foliar Sprays", "Correct micronutrient shortages with foliar feeding.",
     ["Identify the specific deficiency",
      "Choose the correct micronutrient product",
      "Mix at the recommended dose",
      "Spray in the cool hours",
      "Cover both leaf surfaces",
      "Repeat when signs persist",
      "Keep records of results"]),
])


# ============================= EXTRA: EQUIPMENT =============================
add_courses("Equipment", "intermediate", [
    ("Choosing the Right Tractor", "Pick a tractor that fits your farm size and jobs.",
     ["Assess your farm size and tasks",
      "Compare horsepower needs",
      "Check tyre and ground clearance options",
      "Consider fuel and maintenance costs",
      "Look at dealer support and spares",
      "Test drive before buying",
      "Match attachments to the tractor"]),
    ("Tillage Equipment Basics", "Use ploughs and cultivators correctly for seedbed preparation.",
     ["Choose the right implement for the job",
      "Set depth and angle correctly",
      "Work at a steady speed",
      "Avoid over-tilling",
      "Keep blades sharp",
      "Remove stones and debris after use",
      "Service moving parts regularly"]),
    ("Combine Harvester Operation", "Operate and adjust a combine harvester for clean grain.",
     ["Inspect the combine before use",
      "Set reel, cutter and concave correctly",
      "Match ground speed to crop",
      "Check grain loss and clean grain",
      "Stop safely to clear blockages",
      "Keep gathering parts adjusted",
      "Service after the season"]),
    ("Maintaining a Diesel Engine", "Keep a diesel engine (pump/tractor) running reliably.",
     ["Change oil and filters on schedule",
      "Keep the fuel clean",
      "Check coolant and belts",
      "Monitor the air filter",
      "Listen for unusual sounds",
      "Fix leaks promptly",
      "Store the engine protected indoors"]),
    ("Electric Fence Setup for Livestock", "Set up a safe, effective electric fence.",
     ["Plan the fence layout",
      "Install a reliable energizer",
      "Use good insulators and posts",
      "Keep vegetation off the line",
      "Check voltage regularly",
      "Earthing properly for shock strength",
      "Train animals and warn people"]),
    ("Sprayer Nozzle Selection", "Choose the right nozzle for even, accurate spraying.",
     ["Match nozzle to your job",
      "Check droplet size for drift control",
      "Replace worn nozzles",
      "Use the correct pressure",
      "Check spray patterns",
      "Clean nozzles after use",
      "Calibrate output regularly"]),
    ("Irrigation Pump Selection and Care", "Choose and maintain a suitable irrigation pump.",
     ["Match pump size to water need",
      "Know your head and discharge",
      "Install with proper foot valve",
      "Prime correctly before starting",
      "Check for leaks and wear",
      "Protect from freezing or dust",
      "Service the pump regularly"]),
])


# ============================= EXTRA: LIVESTOCK =============================
add_courses("Livestock", "beginner", [
    ("Buffalo Rearing", "Raise healthy buffalo for milk and meat.",
     ["Choose a good dairy buffalo breed",
      "Provide clean housing and water",
      "Feed balanced green and dry fodder",
      "Follow the vaccination schedule",
      "Maintain hygienic milking",
      "Watch for mastitis signs",
      "Keep breeding and health records"]),
    ("Cattle Shed Management", "Maintain a clean, healthy cattle shed.",
     ["Keep the shed dry and aired",
      "Provide clean bedding",
      "Remove dung daily",
      "Ensure clean water and feed areas",
      "Provide shade and drainage",
      "Control flies and parasites",
      "Disinfect regularly"]),
    ("Rabbit Rearing Basics", "Raise healthy rabbits for meat and income.",
     ["Choose a suitable breed",
      "Provide clean, ventilated hutches",
      "Feed quality greens and pellets",
      "Keep water fresh",
      "Provide nesting for litters",
      "Prevent overcrowding",
      "Handle rabbits gently"]),
    ("Duck Farming Management", "Raise ducks for eggs and meat profitably.",
     ["Choose a suitable duck breed",
      "Provide water for ducking",
      "Build clean, secure night shelter",
      "Feed a balanced diet",
      "Protect from predators",
      "Follow vaccination and deworming",
      "Collect eggs daily"]),
    ("Backyard Chicken Care", "Keep a small healthy flock of backyard chickens.",
     ["Build a safe, clean coop",
      "Provide balanced feed and water",
      "Keep the run clean",
      "Follow vaccination schedule",
      "Protect from predators",
      "Collect eggs regularly",
      "Isolate sick birds early"]),
    ("Animal Vaccination Schedules", "Keep your livestock healthy with the right vaccinations.",
     ["Learn the required vaccines for your animals",
      "Follow the recommended timing",
      "Store vaccines properly (cold chain)",
      "Vaccinate healthy animals only",
      "Record each vaccination",
      "Consult a vet if unsure",
      "Repeat booster doses on time"]),
    ("First Aid for Farm Animals", "Handle minor animal injuries and illness safely.",
     ["Keep a basic first-aid kit",
      "Clean wounds with mild antiseptic",
      "Watch for signs of serious illness",
      "Isolate sick animals",
      "Call a vet for serious cases",
      "Handle an injured animal carefully",
      "Record treatments given"]),
])


# ============================= EXTRA: ORGANIC FARMING =============================
add_courses("Organic Farming", "beginner", [
    ("Organic Certification Process", "Understand how to get your farm organically certified.",
     ["Learn the organic standards in your region",
      "Prepare documents and field records",
      "Use only approved inputs",
      "Maintain a transition period",
      "Cooperate with inspection",
      "Keep input and sales records",
      "Renew certification each year"]),
    ("Natural Pest Repellent Plants", "Plant natural repellents to push pests away.",
     ["Grow marigold around crops",
      "Plant neem and other repellents",
      "Add herbs like basil and mint",
      "Position repellents as borders",
      "Combine with other pest control",
      "Renew and manage repellents",
      "Observe which repel best"]),
    ("Organic Disease Control", "Manage plant diseases using natural methods.",
     ["Choose resistant varieties",
      "Space plants for air flow",
      "Water at the base",
      "Remove infected plants quickly",
      "Use compost tea and neem",
      "Rotate crops to break disease",
      "Sanitize tools between rows"]),
    ("Growing Green Manure Organically", "Grow organic cover crops to feed the soil.",
     ["Choose suitable legume covers",
      "Sow after the main harvest",
      "Grow without synthetic inputs",
      "Turn into the soil before flowering",
      "Use the biomass as mulch or compost",
      "Plan timing for the next crop",
      "Repeat each season"]),
    ("Organic Fertilizer Mixes", "Blend simple organic fertilizers on the farm.",
     ["Gather compost, bone meal, and ash",
      "Mix by crop needs",
      "Store dry and covered",
      "Apply before sowing",
      "Combine with liquid organics",
      "Watch plant response",
      "Adjust the mix each season"]),
    ("Zero-Budget Natural Farming", "Reduce input costs with low-cost natural methods.",
     ["Use local, on-farm inputs",
      "Prepare jeevamrut and beejamrut",
      "Mulch and cover the soil",
      "Minimize purchased inputs",
      "Use personal labour wisely",
      "Sell at a premium for organic",
      "Keep cost records to prove savings"]),
])


# ============================= EXTRA: HARVESTING =============================
add_courses("Harvesting", "beginner", [
    ("Timing Crop Harvests", "Harvest at the best time for quality and yield.",
     ["Learn each crop's maturity signs",
      "Check moisture or colour indicators",
      "Harvest in dry conditions where possible",
      "Avoid harvesting too early or late",
      "Plan labour and machines ahead",
      "Match harvest to market demand",
      "Record harvest dates each season"]),
    ("Threshing and Winnowing", "Thresh and winnow grains with minimal loss.",
     ["Dry the harvested plants",
      "Thresh at the correct moisture",
      "Use a clean threshing floor",
      "Remove straw and impurities",
      "Winnow to separate chaff",
      "Collect and bag grain carefully",
      "Dry again before storage"]),
    ("Curing and Drying Produce", "Cure and dry produce to keep it marketable.",
     ["Cure onions, garlic and roots first",
      "Dry produce in the shade where needed",
      "Provide air circulation",
      "Turn produce evenly",
      "Protect from rain and dust",
      "Test for the desired dryness",
      "Store only when fully cured"]),
    ("Cold Storage of Fruits", "Store fruits in controlled cold for longer life.",
     ["Cool fruits soon after harvest",
      "Set the right temperature per fruit",
      "Keep humidity appropriate",
      "Ventilation to remove ethylene",
      "Separate ethylene-producing fruits",
      "Inspect stored fruits regularly",
      "Handle carefully to avoid bruises"]),
    ("Grading and Packaging", "Grade and pack produce to earn better prices.",
     ["Sort by size and quality",
      "Remove damaged or infected items",
      "Use clean, ventilated containers",
      "Pad fragile produce well",
      "Label with grade and weight",
      "Cool before packaging",
      "Transport gently and quickly"]),
    ("Reducing On-Farm Losses", "Cut harvest and storage losses with simple steps.",
     ["Harvest at the right stage",
      "Handle produce gently",
      "Dry and clean properly",
      "Store in pest-free conditions",
      "Keep storage cool and dry",
      "Market or process quickly",
      "Monitor stored produce often"]),
])


# ============================= EXTRA: WEATHER =============================
add_courses("Weather", "beginner", [
    ("Monsoon Preparedness", "Prepare your farm safely for the monsoon season.",
     ["Check weather forecasts regularly",
      "Clean drains and repair bunds",
      "Plan sowing around the rains",
      "Protect seeds and inputs from damp",
      "Store grain above floor level",
      "Stake or support tall crops",
      "Review insurance coverage for the season"]),
    ("Heatwave Safety on the Farm", "Stay safe and protect crops during heatwaves.",
     ["Reschedule work to cooler hours",
      "Drink water and rest in shade",
      "Mulch and water crops early",
      "Provide shade for livestock",
      "Watch for heat stress in animals",
      "Avoid midday field work",
      "Monitor weather alerts"]),
    ("Using Weather Alerts Effectively", "Act on weather alerts to protect your farm.",
     ["Set up alerts on a weather app",
      "Understand the alert types",
      "Act quickly on severe warnings",
      "Protect crops and livestock early",
      "Coordinate with neighbors",
      "Review after each event",
      "Adjust future plans from lessons"]),
    ("Storm and Hail Protection", "Reduce damage to crops and structures from storms.",
     ["Secure loose roofs and structures",
      "Cover seedlings with netting",
      "Stake tall plants",
      "Move livestock to shelter",
      "Store equipment safely",
      "Prepare for fast repairs after",
      "Review insurance for hail cover"]),
    ("Weather and Pesticide Spraying", "Choose the right weather for safe, effective spraying.",
     ["Never spray in strong wind",
      "Avoid spraying before forecast rain",
      "Spray in calm, cool hours",
      "Check temperature for spray effectiveness",
      "Avoid spraying in heat stress",
      "Keep records of weather at spray",
      "Re-spray if washed off by rain"]),
    ("Seasonal Farming Calendar", "Plan farm activities across the seasons.",
     ["Know your region's seasons",
      "Plan sowing and harvest windows",
      "Schedule fertilizer and pest control",
      "Factor in expected rainfall",
      "Prepare for peak labor times",
      "Adapt plans to actual weather",
      "Use the calendar as a working guide"]),
])


# ============================= EXTRA: FINANCE =============================
add_courses("Finance", "intermediate", [
    ("Crop Insurance Basics", "Understand and use crop insurance to reduce risk.",
     ["Learn how crop insurance works",
      "Check which schemes apply to you",
      "Understand premiums and coverage",
      "Register before the deadline",
      "Submit claims for qualifying losses",
      "Keep field and yield records",
      "Review coverage each season"]),
    ("Borrowing for the Farm", "Borrow money wisely for farming needs.",
     ["Compare interest rates and terms",
      "Calculate the affordable repayment",
      "Use loans for productive inputs",
      "Avoid high-cost informal loans",
      "Keep repayment on schedule",
      "Maintain a good credit record",
      "Use KCC where convenient"]),
    ("Selling at the Best Price", "Improve the price you get for your produce.",
     ["Compare mandi and market prices",
      "Gather price information before selling",
      "Consider grading to fetch better rates",
      "Avoid panic selling at harvest",
      "Explore direct and online channels",
      "Store when price is temporary low",
      "Track prices through the season"]),
    ("Cost of Production Analysis", "Know exactly what it costs to grow your crop.",
     ["Add all input costs for the crop",
      "Include labor and machinery costs",
      "Add irrigation and water charges",
      "Total the production cost",
      "Divide by yield for cost per unit",
      "Compare with selling price",
      "Find ways to cut costs"]),
    ("Farm Savings and Emergency Fund", "Build savings to protect your farm from shocks.",
     ["Set aside a small amount regularly",
      "Keep an emergency fund for bad seasons",
      "Separate farm and family money",
      "Save when prices are good",
      "Avoid spending all at harvest time",
      "Use savings for genuine emergencies",
      "Review your savings each year"]),
    ("Using Mobile Money for Farming", "Manage farm money safely with mobile banking.",
     ["Choose a trustworthy mobile wallet/bank",
      "Keep your PIN and phone secure",
      "Pay for inputs digitally and get records",
      "Track spending in the app",
      "Receive money sales directly",
      "Set transfer limits for safety",
      "Guard against scams"]),
])


# ============================= EXTRA: HORTICULTURE / OTHERS =============================
add_courses("Horticulture", "beginner", [
    ("Mango Orchard Establishment", "Plant and establish a healthy mango orchard.",
     ["Choose a suitable mango variety",
      "Prepare pits with good soil",
      "Plant grafted trees at the right spacing",
      "Provide initial watering and staking",
      "Manage young trees with pruning",
      "Control pests like fruit fly later",
      "Plan years to first yield"]),
    ("Grape Vineyard Management", "Grow and train healthy grapevines.",
     ["Choose varieties for your climate",
      "Establish a proper trellis system",
      "Train vines to the correct shape",
      "Manage irrigation and nutrition",
      "Prune at the right time for quality",
      "Protect against downy mildew",
      "Harvest at peak sugar"]),
    ("Papaya Cultivation", "Grow a fast-yielding papaya crop.",
     ["Choose a high-yield variety",
      "Prepare well-drained soil",
      "Plant at correct spacing",
      "Sex the plants and keep females",
      "Provide water and fertilizer",
      "Control virus through sanitation",
      "Harvest fruits at the right stage"]),
    ("Citrus Orchard Care", "Care for citrus trees for juicy, quality fruit.",
     ["Water regularly without over-watering",
      "Fertilize with leaf and fruit needs",
      "Prune to open the canopy",
      "Control citrus mites and leaf miner",
      "Protect from frost",
      "Harvest at the right ripeness",
      "Grade and pack fruits carefully"]),
    ("Strawberry Cultivation", "Grow a profitable strawberry crop with care.",
     ["Choose suited runners or tissue plants",
      "Plant on well-drained ridges",
      "Mulch to keep fruit clean",
      "Fertigate and water consistently",
      "Hand-pollinate if needed",
      "Harvest berries at full colour",
      "Cool and market quickly"]),
    ("Floriculture Basics", "Grow and market flowers profitably.",
     ["Choose market-demand flower crops",
      "Prepare rich, well-drained beds",
      "Plant at correct spacing",
      "Manage water and harvesting",
      "Harvest at the right stage",
      "Grade and pack flowers well",
      "Access urban flower markets"]),
])


add_courses("Farm Technology", "intermediate", [
    ("Using Farm Apps", "Use apps to manage crops, finance and market.",
     ["Choose apps relevant to your farm",
      "Record crops, tasks and expenses",
      "Get weather and market information",
      "Set reminders for activities",
      "Sync data and keep it updated",
      "Use insights to plan better",
      "Keep your data secure"]),
    ("Drone Basics for Farming", "Understand how drones can help monitor crops.",
     ["Learn drone rules and permits",
      "Use drones for crop scouting",
      "Capture field imagery for health checks",
      "Plan drone services carefully",
      "Fly safely and responsibly",
      "Hire trained operators if needed",
      "Combine with ground inspection"]),
    ("GPS Farm Mapping", "Map your farm fields for better management.",
     ["Use GPS to mark field boundaries",
      "Record plot sizes and crops",
      "Map problem zones",
      "Plan inputs using the map",
      "Update maps each season",
      "Share maps with workers/experts",
      "Keep the data backed up"]),
    ("Farm Automation Basics", "Understand simple automation to save labour.",
     ["Identify repetitive farm tasks",
      "Automate irrigation timers",
      "Consider simple sensor controls",
      "Count the cost vs savings",
      "Keep systems simple and reliable",
      "Train users on the equipment",
      "Maintain systems regularly"]),
    ("Dairy Farm Technology", "Use simple tech to manage a dairy herd.",
     ["Record milk yield per animal",
      "Track feeding and health data",
      "Use heat detection techniques",
      "Manage breeding records digitally",
      "Monitor feed and costs",
      "Use tech to save time",
      "Keep software and data secure"]),
])


add_courses("Sustainable Farming", "intermediate", [
    ("Agroforestry Basics", "Combine trees with crops for multiple benefits.",
     ["Choose tree species suited to your farm",
      "Plant trees as borders or blocks",
      "Avoid over-shading crops",
      "Harvest multiple products",
      "Improve soil with leaf litter",
      "Provide wind and shade protection",
      "Plan long-term tree management"]),
    ("Conservation Tillage", "Reduce tillage to protect soil and save fuel.",
     ["Minimize and avoid deep ploughing",
      "Keep crop residues on the surface",
      "Match residues to soil type",
      "Control weeds with residue and rotation",
      "Use mulch and cover crops",
      "Monitor soil moisture",
      "Adopt gradually and observe results"]),
    ("Integrated Farming Systems", "Combine crops, livestock and fish for more income.",
     ["Plan activities that support each other",
      "Use livestock waste as fertilizer",
      "Feed crop by-products to animals",
      "Recycle water between units",
      "Reduce external inputs",
      "Spread income across seasons",
      "Review the system annually"]),
    ("Water Conservation on the Farm", "Conserve water with simple, effective practices.",
     ["Mulch to reduce evaporation",
      "Use efficient irrigation",
      "Improve soil organic matter",
      "Harvest rainwater",
      "Reduce runoff with bunds",
      "Fix leaks and manage wisely",
      "Reuse water where safe"]),
    ("Biodiversity on the Farm", "Encourage beneficial life on your farm.",
     ["Keep native plants and hedges",
      "Provide habitat for pollinators",
      "Avoid over-spraying chemicals",
      "Use minimal tillage",
      "Rotate crops and interplant",
      "Manage a variety of crops",
      "Observe and protect natural enemies"]),
    ("Renewable Energy for Farms", "Use renewable energy to cut farm costs.",
     ["Assess solar for irrigation",
      "Use solar for lighting and fencing",
      "Compare cost with grid power",
      "Store or use energy wisely",
      "Protect and maintain equipment",
      "Explore biogas from waste",
      "Plan payback over time"]),
])


add_courses("Aquaculture", "intermediate", [
    ("Freshwater Fish Farming", "Raise freshwater fish in ponds profitably.",
     ["Choose a suitable fish species mix",
      "Prepare and lime the pond",
      "Manage water quality",
      "Stock the right species and density",
      "Feed quality feed on schedule",
      "Monitor oxygen and health",
      "Harvest at market size"]),
    ("Prawn/Shrimp Farming", "Grow prawns in ponds with good management.",
     ["Choose a suitable prawn species",
      "Set up saline, well-managed ponds",
      "Maintain water quality and salinity",
      "Stock healthy juveniles",
      "Feed and monitor growth",
      "Control disease with hygiene",
      "Harvest and handle carefully"]),
    ("Integrated Fish-Livestock Farming", "Combine fish with livestock for extra income.",
     ["Design ponds to recycle wastes",
      "Use livestock manure to fertilize water",
      "Maintain balanced stocking",
      "Feed both fish and animals well",
      "Monitor water quality",
      "Prevent over-fertilization",
      "Harvest and market both products"]),
    ("Nursery Pond Management", "Raise fish seed in nursery ponds for restocking.",
     ["Prepare a clean, weed-free nursery",
      "Control predators and pests",
      "Feed fry with suitable feed",
      "Maintain oxygen and water quality",
      "Watch stocking density",
      "Grow fry to fingerling size",
      "Harden and transport carefully"]),
])


# ============================= Extra: Crop Management (more) =============================
add_courses("Crop Management", "beginner", [
    ("Okra Cultivation", "Grow a productive okra (lady's finger) crop.",
     ["Choose a high-yield variety",
      "Sow treated seed at the right spacing",
      "Prepare well-drained, fertile beds",
      "Water consistently during flowering",
      "Control yellow vein mosaic and fruit borer",
      "Harvest tender pods regularly",
      "Market fresh to reduce losses"]),
    ("Cluster Bean Cultivation", "Grow a healthy cluster bean (guar) crop.",
     ["Select a suitable variety",
      "Sow at the recommended spacing",
      "Control sucking pests early",
      "Manage water at critical stages",
      "Harvest tender pods",
      "Dry and clean seed if saving",
      "Rotate to avoid disease build-up"]),
    ("Spinach Cultivation", "Grow fresh, marketable leafy spinach.",
     ["Choose a fast-growing variety",
      "Prepare rich, loose beds",
      "Sow seed densely in rows",
      "Water regularly for tender leaves",
      "Control leaf miner and weeds",
      "Harvest leaves at the right stage",
      "Water after each cutting for regrowth"]),
    ("Fenugreek Cultivation", "Grow fenugreek for leaves and seed income.",
     ["Choose a dual-purpose variety",
      "Sow at the correct spacing",
      "Provide light irrigation",
      "Control weeds early",
      "Cut leaves for market, then seed",
      "Harvest mature seed pods",
      "Dry and clean seed for sale"]),
    ("Radish Cultivation", "Grow crisp, quality radish quickly.",
     ["Choose a suited variety",
      "Prepare deep, loose beds",
      "Sow seed directly in rows",
      "Thin to correct spacing",
      "Keep soil moist",
      "Harvest roots at the right size",
      "Grade and market fresh"]),
    ("Peas Cultivation", "Grow a profitable field/garden pea crop.",
     ["Choose a variety for your season",
      "Inoculate seed with Rhizobium",
      "Provide support for climbing types",
      "Sow at the right spacing",
      "Manage water and weeds",
      "Control powdery mildew and pod borers",
      "Harvest pods at tender stage"]),
])


# ============================= Extra Soil (intermediate) =============================
_extra_soil = [
    ("Loamy Soil Management", "Manage loamy soils for maximum productivity.",
     ["Understand the balanced character of loam",
      "Add organic matter to maintain structure",
      "Avoid compaction from heavy machinery",
      "Rotate crops to keep nutrients balanced",
      "Mulch to conserve moisture",
      "Test soil periodically",
      "Adjust drainage where needed"]),
    ("Sandy Soil Improvement", "Improve water and nutrient-holding in sandy soils.",
     ["Add plenty of compost and organic matter",
      "Mulch to reduce water loss",
      "Use split fertilizer doses",
      "Choose drought-tolerant crops",
      "Irrigate more frequently, less volume",
      "Use cover crops to build soil",
      "Avoid over-tillage"] ),
    ("Clay Soil Management", "Manage heavy clay soils for better drainage and aeration.",
     ["Improve drainage with raised beds",
      "Add organic matter to open the soil",
      "Avoid working wet clay soil",
      "Plough at the right moisture",
      "Use gypsum where needed",
      "Mulch and reduce compaction",
      "Choose crops suited to clay"]),
    ("Testing Soil Nutrients", "Check soil nutrients to correct shortages on time.",
     ["Test soil regularly (every 2-3 years)",
      "Sample at the correct depth",
      "Look at nitrogen, phosphorus and potassium",
      "Check secondary and micronutrients",
      "Compare with crop needs",
      "Apply only the missing nutrients",
      "Retest after amendments"]),
    ("Building Organic Matter in Soil", "Raise soil organic matter for healthier crops.",
     ["Add compost and manure each season",
      "Grow and turn in cover crops",
      "Leave crop residues on the field",
      "Reduce burning of residues",
      "Mulch between rows",
      "Avoid excessive tillage",
      "Monitor organic matter over time"]),
]
add_courses("Soil", "intermediate", _extra_soil)


# ---------------------------------------------------------------------------
# Seeder
# ---------------------------------------------------------------------------

def _upsert_course(db, data):
    """Insert a course (and its lesson + quiz) if it does not yet exist by title."""
    existing = db.query(Course).filter(Course.title == data["title"]).first()
    if existing:
        return None

    course = Course(
        course_id=generate_id("FA-CRS", db, Course),
        title=data["title"],
        description=data["description"],
        category=data["category"],
        level=data["level"],
        duration_weeks=data.get("duration_weeks"),
        language="English",
        instructor=data["instructor"],
        video_url=data.get("video_url") or "",
        core_content=data.get("core_content"),
        tools_materials=data.get("tools_materials"),
        safety_tips=data.get("safety_tips"),
        total_lessons=1,
        is_published=True,
    )
    db.add(course)
    db.flush()

    # Single tutorial lesson holds the core content and hosts the quiz.
    lesson = CourseLesson(
        lesson_id=f"T{course.course_id.split('-')[-1]}",
        course_id=course.id,
        title=f"{data['title']} - Tutorial",
        description=data.get("core_content"),
        content=data.get("core_content"),
        content_type="text",
        order_index=0,
        duration_minutes=20,
        is_published=True,
    )
    db.add(lesson)
    db.flush()

    quiz = data.get("quiz") or [
        _q(
            f"What is the first practical step recommended in '{data['title']}'?",
            ["Prepare/select correctly for your field", "Skip all field preparation",
             "Immediately harvest", "Stop all irrigation"],
            0,
            "Every practical course begins with proper selection and preparation.",
        ),
        _q(
            "Why are safety and tool preparation important?",
            ["To work safely and effectively", "To raise costs", "To slow down work", "They are not important"],
            0, "Preparing tools and following safety protects both you and the crop.",
        ),
        _q(
            "What should you do when a problem appears mid-season?",
            ["Scout, identify and act early", "Ignore it", "Harvest early", "Use extra everything"],
            0, "Early scouting and correct identification let you manage problems in time.",
        ),
    ]

    for i, q in enumerate(quiz):
        qid = f"Q{course.course_id.split('-')[-1]}-{i+1}"
        db.add(LearningQuestion(
            question_id=qid,
            tutorial_id=lesson.id,
            course_id=course.id,
            question=q["question"],
            option_1=q["options"][0],
            option_2=q["options"][1],
            option_3=q["options"][2],
            option_4=q["options"][3],
            correct_answer=q["correct"],
            explanation=q.get("explanation", ""),
            order_index=i,
        ))

    return course


def seed_learning(db):
    """Idempotently seed learning courses. Returns a summary dict."""
    created = 0
    existing = 0
    for data in COURSES:
        course = _upsert_course(db, data)
        if course is not None:
            created += 1
        else:
            existing += 1
    db.commit()
    total = db.query(Course).count()
    return {
        "created": created,
        "already_existing": existing,
        "total_courses": total,
    }


if __name__ == "__main__":
    db = SessionLocal()
    try:
        res = seed_learning(db)
        print("Learning seeding complete:", res)
    finally:
        db.close()
